services:
  - type: web
    name: ecomm-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    healthCheckPath: /swagger-ui.html
    envVars:
      - key: SPRING_SECURITY_USER_NAME
        sync: false
      - key: SPRING_SECURITY_USER_PASSWORD
        sync: false
      - key: SPRING_APP_JWT_SECRET
        sync: false
      - key: SPRING_APP_JWT_EXPIRATION_MS
        value: "300000000"
      - key: SPRING_ECOM_APP_JWT_COOKIE_NAME
        value: "ecomm-cookie"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: APP_COOKIE_SECURE
        value: "true"
      - key: APP_COOKIE_SAME_SITE
        value: "none"
      - key: APP_COOKIE_DOMAIN
        sync: false
